config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "/login", to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/dashboard', to: "users#show"
  post '/items/search', to: "items#search"

  resource :cart, only: [:create, :show, :destroy, :update]
  resources :items, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :create, :show]

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    get '/edit', to: "users#edit"
    patch '/edit', to: "users#update"
    get '/analytics-dashboard', to: "analytics#index"
    post '/analytics-dashboard', to: "analytics#index"
    get '/filter', to: "dashboard#index"
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  get "/:category_slug", to: "categories#show"

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController

  def index
    if params[:status] == "All" || !params[:status]
      @orders = Order.ordered_by_id
    else
      @orders = Order.where(status: params[:status])
    end
    @orders_by_status = Order.group_by_status_count
    @statuses = Order.pluck(:status).uniq.unshift("All")
  end

end

app/views/admin/dashboard/index.html.erb
<h1>Admin Dashboard</h1>
<div class="admin-header-links">
  <div class="row-flexbox">
    <%= link_to "Edit Account Information", admin_edit_path, class: "standard-box" %>
    <%= link_to "Analytics Dashboard", admin_analytics_dashboard_path, class: "standard-box" %>
    <%= link_to "Item Index", admin_items_path, class: "standard-box" %>
    <%= link_to "Create Item", new_admin_item_path, class: "standard-box" %>
  </div>
</div>
    <div class="admin-dashboard-box">
    <h2>All Orders</h2>
    <%= form_tag('/admin/filter', method: 'get') do %>
      <%= label_tag "Filter By:" %>
      <%= select_tag :status, options_for_select(@statuses) %>
      <%= submit_tag "Submit"%>
    <% end  %>
    <table class="order-table">
      <tr>
        <th>Order ID</th>
        <th>Order Status</th>
        <th>Order Placed On</th>
        <th>Order Updated On</th>
        <th>Order Total Price</th>
        <th>Change Order Status</th>
      </tr>
      <% @orders.each do |order| %>
      <tr>
        <th><%= link_to order.id, admin_order_path(order) %></th>
        <th><%= order.status %></th>
        <th><%= order.created_at.strftime("%b %d, %Y") %></th>
        <th><%= order.updated_at.strftime("%b %d, %Y") %></th>
        <th><%= order.total_item_price %></th>
        <th>
          <% if order.status.downcase == "ordered"%>
            <%= button_to "Mark as paid", admin_order_path(order, update_status: "Paid"), method: :patch %>
            <%= button_to "Cancel order", admin_order_path(order, update_status: "Cancelled"), method: :patch %>
          <% elsif order.status.downcase == "paid" %>
            <%= button_to "Mark as completed", admin_order_path(order, update_status: "Completed"), method: :patch %>
            <%= button_to "Cancel order", admin_order_path(order, update_status: "Cancelled"), method: :patch %>
          <% end %>
        </th>
      </tr>
      <% end %>
    </table>
    <h2>Order Count by Status</h2>
    <table class="order-status-table">
      <tr>
        <th>Order Status</th>
        <th>Order Count</th>
      </tr>
      <% @orders_by_status.each do |status, count|%>
      <tr>
        <th><%= status %></th>
        <th><%= count %></th>
      </tr>
      <% end %>
    </table>
</div>