config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "/login", to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/dashboard', to: "users#show"
  post '/items/search', to: "items#search"

  resource :cart, only: [:create, :show, :destroy, :update]
  resources :items, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :create, :show]

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    get '/edit', to: "users#edit"
    patch '/edit', to: "users#update"
    get '/analytics-dashboard', to: "analytics#index"
    post '/analytics-dashboard', to: "analytics#index"
    get '/filter', to: "dashboard#index"
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  get "/:category_slug", to: "categories#show"

end

app/views/partials/_item_form.html.erb
<div class="column-flexbox">
  <%= form_for [:admin, @item], html: {id: "create-item-form"} do |f| %>
  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <%= f.label :image, "Image URL"%>
  <%= f.text_area :image %>
  <%= f.label :category_id %>
  <%= f.select :category_id, @categories.collect {|category| category.name} %>
  <br>
  <div>
    <%= f.radio_button :status, 'active', :checked => true %>
    <%= f.label :status, 'Active' %>
    <%= f.radio_button :status, 'retired' %>
    <%= f.label :status, 'Retired' %>
  </div>
  <br>
    <%= f.submit class: "submit-button" %>
  <% end %>
</div>

app/views/partials/_item_render.html.erb
<div class="item_attributes">
  <%= item.name %>
  <%= link_to(image_tag(image_path("#{item.image}"), class: "item-image" ), item_path(item))%>
  <%= number_to_currency(item.price) %>
  <% if item.status == "active" %>
    <%= button_to "Add To Cart", cart_path(item_id: item.id) %>
  <% elsif item.status == "retired" %>
    <p class="retired-button">--Item Retired--</p>
  <%end%>
</div>

app/views/partials/_order_table.html.erb
<div id="user-show">

<div id="user-block">
  <h1>Your Recent Orders</h1>
  <div id="user-table">
    <table>
      <tr>
        <th>Order ID</th>
        <th>Status</th>
        <th>Total Price</th>
        <th>Address</th>
        <th>Item Count</th>
      </tr>
    <% current_user.orders.each do |order| %>
      <tr>
        <th><%= link_to order.id, order_path(order), class: "order#{order.id}" %></th>
        <th><%= order.status %></th>
        <th><%= number_to_currency(order.total_price) %></th>
        <th><%= order.user.address %></th>
        <th><%= order.items.count %></th>
      </tr>
    <% end %>
    </table>
  </div>
  <div id="login-shop-pair">
    <div >
      <%= link_to "Shop Now!", items_path, class: "user-page-button" %>
    </div>
    <div>
      <%= link_to "Browse Categories", categories_path, class: "user-page-button" %>
    </div>
  </div>
</div>
</div>