config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "welcome#index"
  get "/login", to: "sessions#new"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  get '/dashboard', to: "users#show"
  post '/items/search', to: "items#search"

  resource :cart, only: [:create, :show, :destroy, :update]
  resources :items, only: [:index, :show]
  resources :users, only: [:new, :create, :show]
  resources :categories, only: [:index]
  resources :orders, only: [:index, :create, :show]

  namespace :admin do
    get '/dashboard', to: "dashboard#index"
    get '/edit', to: "users#edit"
    patch '/edit', to: "users#update"
    get '/analytics-dashboard', to: "analytics#index"
    post '/analytics-dashboard', to: "analytics#index"
    get '/filter', to: "dashboard#index"
    resources :orders, only: [:show, :update]
    resources :items, only: [:index, :new, :create, :edit, :update]
  end

  get "/:category_slug", to: "categories#show"

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(contents)
    @contents = contents || Hash.new(0)
  end

  def count_of(id)
    contents[id.to_s]
  end

  def cart_items
    contents.transform_keys do |key|
      Item.find(key.to_i)
    end
  end

  def add_item(id)
    contents[id.to_s] = (contents[id.to_s] || 0) + 1
  end

  def total_cost
    cart_items.map {|item, count| item.price * count}.sum
  end

  def remove_item(id)
    contents.delete(id.to_s)
  end

  def item_quantity
    contents.values.sum
  end


  def create_order_items(order)
    contents.each do |item_id, quantity|
      order_item = OrderItem.create!(order_id: order.id,
                                     item_id: item_id.to_i,
                                     original_price: Item.find(item_id.to_s).price,
                                     quantity: quantity)
      order_item.update(sub_total: order_item.original_price * order_item.quantity)
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    flash[:notice] = "#{pluralize(@cart.count_of(item.id), item.name)} added to your cart!"
    redirect_to request.referrer
  end

  def show
    @items = @cart.cart_items
  end

  def destroy
    @item = Item.find(params[:item_id])
    @cart.remove_item(@item.id)
    session[:cart] = @cart.contents
    flash[:notice] = "#{view_context.link_to(@item.name, item_path(@item), class: "flash-remove-item")} was removed from your cart!"
    redirect_to cart_path
  end

  def update
    if params[:quantity].to_i <= 0
      session[:cart].delete(params[:item_id].to_s)
    else
      session[:cart][(params[:item_id]).to_s] = (params[:quantity]).to_i
    end
    redirect_to cart_path
  end


end

app/views/carts/show.html.erb
<h1>My Cart</h1>

<div id="cart-view">
  <% if @items.empty?  %>
    <p class="empty-cart">Your cart is empty</p>
  <% else %>
    <% @items.each do |item, count| %>
    <div id="cart-item">
      <% if count > 0 %>
        <%= link_to item_path(item) do %>
           <%= image_tag "#{item.image}", class: "cart-image" %>
        <% end %>
        <div id="cart-item-show">
          <p id="cart-item-name"><%= item.name%></p>
          <%= item.description %><br><br>
          <div id="price-subtotal">
            <div>
              Price: <%= number_to_currency(item.price) %>
            </div>
            <div>
              Count: <%= count %>
            </div>
            <div>
              Subtotal: <%= number_to_currency(count * item.price) %>
            </div>
          </div>
        </div>
        <div id="quantity-remove">
          <div id="quantity">
            <%= form_tag("/cart", method: "put") do %>
              <%= hidden_field_tag "item_id", item.id %>
              <%= label_tag "Quantity" %>
              <%= number_field_tag :quantity %>
              <%= submit_tag "Update" %>
            <% end %>
          </div>
        <%= link_to "Remove Item", cart_path(item_id: item.id), method: :delete %>
      </div>
        <% else %>
          <% @cart.remove_item(item.id) %>
        <% end %>
      </div>
    <% end %>
    <div id="total-cost">
      Total Cost: <%= number_to_currency(@cart.total_cost) %>
      <div id="checkout">
        <% if current_user %>
          <%= link_to "Checkout", orders_path, method: :post %>
          <% else %>
          <%= link_to "Login or Create Account to Checkout", login_path %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>